### ISSUE TITLE
关于一些python库的安装

### ISSUE THREAD

**Issue by T-AD** [munhouiani/Deep-Packet#10]
本机为Windows10系统，在安装pytorch_lightning和petastorm时出现安装错误，且在预处理时在命令行输入python preprocessing.py -s D:\DP\deeppacket\ISCX数据集\CompletePcap -t processed_data -n 1时出现错误，其中D:\DP\deeppacket\ISCX数据集\CompletePcap为全部数据集文件的路径，processed_data为与preprocessing.py在同一文件夹的空文件夹，运行至中途出错，使得processed_data已有部分parquet文件，不知是否与两个库没装以及电脑自身问题有关

**Comment by munhouiani** [comment]
Code 已更新
