### ISSUE TITLE
关于运行train_cnn.py出错的问题

### ISSUE THREAD

**Issue by flzer** [munhouiani/Deep-Packet#11]
电脑为Windows 10系统，python版本为 3.9.1
在使用cmd控制台运行train_cnn.py时，出现 **AttributeError: can't set attribute** 错误，请问如何解决？
输入的命令行参数如下：
**python train_cnn.py -d** F:\Deep-Packet-master\testin **-m** F:\Deep-Packet-master\modeltest **-t traffic**
感谢~

**Comment by QzP-QD** [comment]
同问，我也出现同样的问题。。

**Comment by munhouiani** [comment]
Code 已更新
