### ISSUE TITLE
训练时间太久

### ISSUE THREAD

**Issue by QzP-QD** [munhouiani/Deep-Packet#16]
大佬您好，我尝试运行了您的代码，在训练app分类器，但是第一个epoch的训练就用了很久，这是为什么呢？是正常的吗？
![image](https://user-images.githubusercontent.com/42259825/145209506-a0e5be40-b42f-42f5-93db-025dfed42f55.png)

**Comment by QzP-QD** [comment]
4个小时16分钟还没有跑完，感觉是不是出问题了

**Comment by munhouiani** [comment]
Code 已更新，附上訓練時間
https://github.com/munhouiani/Deep-Packet#elapsed-time
