### ISSUE TITLE
关于create_train_test.py问题

### ISSUE THREAD

**Issue by wangnannan2333** [munhouiani/Deep-Packet#22]
想请问一下~
为什么执行了此py文件后
parquet文件的大小会减小很多？

**Comment by munhouiani** [comment]
同 https://github.com/munhouiani/Deep-Packet/issues/17#issuecomment-1013428752

**Comment by wangnannan2333** [comment]
![image](https://user-images.githubusercontent.com/39640266/163704047-a2787efe-9b82-40fd-b295-e1575e7438e6.png)
另外我在预测时显示的打印出来的混淆矩阵的图像，只有一类的准确率，而我在测试时的数据有10类，请问您知道这是哪里出了问题嘛~
