### ISSUE TITLE
pre-train model

### ISSUE THREAD

**Issue by wangnannan2333** [munhouiani/Deep-Packet#23]
您好，预训练模型的链接再次失效，请问可以更新一下链接嘛~

**Comment by munhouiani** [comment]
我目前看是沒有問題的，你再試試

**Comment by wangnannan2333** [comment]
> 我目前看是沒有問題的，你再試試

您好，再次试了还是无法打开，可否麻烦您发一份到1430719579@qq.com邮箱呢，万分感谢~
