### ISSUE TITLE
The result of evaluation.ipynb

### ISSUE THREAD

**Issue by zzh-z** [munhouiani/Deep-Packet#28]
Hello, I'm using this repo. I notice that the results in [evaluation.ipynb](https://github.com/munhouiani/Deep-Packet/blob/master/evaluation.ipynb)  are not very consistent with the paper, especially the precision will be lower, why is this?

Thank you!

**Comment by munhouiani** [comment]
Data distribution could be one of the reasons. I didn't know how the authors categorized and split their data, so I did this with my best guess
