### ISSUE TITLE
cannot convert float NaN to integer

### ISSUE THREAD

**Issue by wladradchenko** [munhouiani/Deep-Packet#38]
Dear owner, 

I wanted to test the code and I have tried to start the `python create_train_test_set.py -s processed_data -t train_test_data` code after `python preprocessing.py -s data/VPN-PCAPS-01/ -t processed_data`. I used dataset from README [VPN-PCAPS-01.zip](https://www.unb.ca/cic/datasets/vpn.html). 

I got an error cannot convert float NaN to integer in 57 line: `min_label_count = int(label_count_df["count"].min())`. Of course I can change the line as `min_label_count = int(label_count_df["count"].min()) if not label_count_df["count"].empty else 0`, but I understand that data from packet is empty and after finished the code the data will be empty. 

If I run the code as `python create_train_test_set.py -s processed_data -t train_test_data --under_sampling False` (1), than I will be able get some result:

   label   count
0      7   15991
1      6  127016
2      9  269115
3      5   40164
4     10  900984

I will get an error `Please pass `features` or at least one example when writing data` in evaluation_cnn.ipynb line 6 with [model](https://drive.google.com/file/d/1LFrx2us11cNqIDm_yWcfMES5ypvAgpmC/view?usp=sharing) on the output of result (1) train_test_data.

How I need to start `python create_train_test_set.py -s processed_data -t train_test_data` after preprocessing.py? Because the instruction is not full in the current README. 

Also, it's not clear for me how you set label for pcap packets? I saw that you used `prefix = path.name.split(".")[0].lower()`. I'm not sure that used name of file is good idea to set class for NN learning. Why you don't use the IP list? How I can understand that the model works clear if I can't see labels by IP? 

Thanks.

**Comment by VladRadchenko** [comment]
And if you take the model from README, then the result looks like the recognition does not work. So, I'm not sure in correct Evaluation Result. I have inspected on PCAPs with label Facebook, Skype, Youtube, VPN.

**Comment by 365ms** [comment]
Try to correct the processed_data ,open one of the .json file,check the app_label and traffic_label ，if value is null that means u should add the specific prefix-id according to your dataset in utlis.py
