### ISSUE TITLE
Approach flawed if ports left in dataset

### ISSUE THREAD

**Issue by Mr-Pepe** [munhouiani/Deep-Packet#41]
I just stumbled upon this repository and it looks like only IP information is removed from the dataset. Are you aware of [this](https://github.com/mr-pepe/iscx-analysis)? I find it hard to believe that your model actually learned anything besides the mapping of network flows to traffic classes.

**Comment by munhouiani** [comment]
> Are you aware of [this](https://github.com/mr-pepe/iscx-analysis)?

No, I didn't. I was researching the usage of deep learning in packet classification several years ago and found the Deep packet paper. The authors didn't publish their code online, so I implemented it myself in PyTorch. I didn't look into the data, so you might be right. The model could be just mapping the network flows to traffic classes.
