### ISSUE TITLE
Why "remove tor and torrent related data as they are no longer available" mean?

### ISSUE THREAD

**Issue by pao0626** [munhouiani/Deep-Packet#44]
I would like to ask what the exact definition of "no longer available" is. Is there an error in the data set? Or does the modern Internet world not recognize tornet?
Thanks!

**Comment by munhouiani** [comment]
The last time I checked the raw dataset I found that it no longer contains tor and torrent-related data, e.g. `Torrent`, `Tor` for application classification, and `Torrent`, `VPN: Torrent` from traffic classification.
