### ISSUE TITLE
标签问题

### ISSUE THREAD

**Issue by Cyan95** [munhouiani/Deep-Packet#6]
preprocessing.py中根据文件名前缀来获取app label和traffic label。
但PREFIX_TO_APP_ID和PREFIX_TO_TRAFFIC_ID里的前缀都没有完全覆盖完整的数据集。
是不是某些数据包文件只参与一种分类任务？

**Comment by munhouiani** [comment]
是的，其實原始論文裡對於這一塊的描述也是很模糊的
我就憑自己的理解，針對這兩種任務盡可能地提取可用的資料集

**Comment by Cyan95** [comment]
你的这个项目对我帮助很大。
祝你新年快乐，学术事业更上一层楼！
