### ISSUE TITLE
pre-traind模型使用出错

### ISSUE THREAD

**Issue by zbdxkzk** [munhouiani/Deep-Packet#8]
求助求助！！！

**Comment by zbdxkzk** [comment]
运行时出现了这个错误
TypeError: __init__() missing 1 required positional argument: 'hparams'

**Comment by LSC666** [comment]
> > 运行时出现了这个错误 TypeError: **init**() missing 1 required positional argument: 'hparams'
> 
> 猜测可能是使用了较新版本的 pytorch-lightning，新的版本更改了 hparams 参数的用法：https://pytorch-lightning.readthedocs.io/en/latest/common/hyperparameters.html

请问哪个版本的可以用啊？我试了好几个版本都不可以。

**Comment by LSC666** [comment]
pytorch-lightning-0.9.0  这个版本可以用 @zbdxkzk

**Comment by munhouiani** [comment]
Code 已更新
